version: '3.5'
services:
  consumer:
    tty: true
    build: ./consumer
    restart: always
    links:
      - rabbitmq
      - db

  rabbitmq:
    tty: true
    image: rabbitmq
    ports:
      - 5672:5672

  db:
    build: ./postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
