version: '3.5'
services:
  django:
    tty: true
    build: .
    ports:
      - 8000:8000
    links:       
      - db
    volumes:
      - .:/django
    command:
      - /bin/sh
      - -c
      - |
         ./manage.py makemigrations
         ./manage.py migrate
         ./manage.py runserver 0.0.0.0:8000
  db:
    build: ./postgres
    tty: true
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data


